---
- name: 'Setup-luks: Open the LUKS device'
  community.crypto.luks_device:
    device: '/dev/disk/by-id/{{ LUKS_device.name }}'
    state: 'opened'
    name: '{{ LUKS_device.name }}'
    passphrase: '{{ LUKS_device.pass }}'
  loop: '{{ LUKS_devices }}'
  loop_control:
    loop_var: 'LUKS_device'
  no_log: true

- name: 'Setup-luks: Setup crypptab'
  community.general.crypttab:
    name: '{{ LUKS_device.name }}'
    backing_device: '/dev/disk/by-id/{{ LUKS_device.name }}'
    password: '{{ LUKS_device.pass }}'
    opts: luks
    state: present
  loop: '{{ LUKS_devices }}'
  loop_control:
    loop_var: 'LUKS_device'
  no_log: true
