---
- name: 'Setup-luks: Send the keyfile over to the target machine.'
  ansible.builtin.copy:
    dest: '/root/{{ LUKS_device.name }}_key'
    owner: 'root'
    group: 'root'
    mode: '0400'
    content: |
      {{ LUKS_device.pass }}
  loop: '{{ LUKS_devices }}'
  loop_control:
    loop_var: 'LUKS_device'
  no_log: true

- name: 'Setup-luks: Open the LUKS device'
  community.crypto.luks_device:
    device: '/dev/disk/by-id/{{ LUKS_device.name }}'
    state: 'opened'
    name: '{{ LUKS_device.name }}'
    keyfile: '/root/{{ LUKS_device.name }}_key'
  loop: '{{ LUKS_devices }}'
  loop_control:
    loop_var: 'LUKS_device'
  no_log: true

- name: 'Setup-luks: Setup crypptab'
  community.general.crypttab:
    name: '{{ LUKS_device.name }}'
    backing_device: '/dev/disk/by-id/{{ LUKS_device.name }}'
    password: '/root/{{ LUKS_device.name }}_key'
    opts: luks
    state: present
  loop: '{{ LUKS_devices }}'
  loop_control:
    loop_var: 'LUKS_device'
  no_log: true
