---
- name: 'pre-setup: Install required packages'
  apt:
    name: '{{ item.name }}'
    state: 'present'
    update_cache: true
  loop: '{{ nginx_packages }}'

- name: 'pre-setup: Add pgp key for nginx'
  apt_key:
    id: '573BFD6B3D8FBC641079A6ABABF5BD827BD9BF62'
    url: 'http://nginx.org/keys/nginx_signing.key'

- name: 'pre-setup: Setup nginx repository'
  apt_repository:
    filename: 'nginx'
    repo: 'deb [arch=amd64] https://nginx.org/packages/mainline/ubuntu/ bionic nginx'
    update_cache: yes
    mode: 0644
