---
- name: 'setup_mounts: Mount the various shares'
  mount:
    state: mounted
    name: "{{ nfs_mount_base_mountpoint }}/{{ mount.mount_point }}"
    src: "{{ mount.server }}:/{{ mount.share_name }}"
    fstype: "{{ mount.filesystem }}"
    opts: "{{ mount.opts }}"
    dump: '0'
    passno: '0'
  loop: "{{ nfs_mounts }}"
  loop_control:
    loop_var: "mount"
