---
galaxy_info:
  role_name: "virtiofs_client"
  author: "Michalis Michaloliakos <michalis.michaloliakos@gmail.com>"
  description: "Setting up a host to mount virtiofs filesystems"
  company: "Home"
  license: Internal
  min_ansible_version: "2.9"
  platforms:
    - name: Ubuntu
      versions:
        - bionic

dependencies: []

