---
galaxy_info:
  role_name: "cloud_vm"
  author: "Michalis Michaloliakos <michalis.michaloliakos@gmail.com>"
  description: "Tasks to be performed in a cloud_vm to clean it up through Packer"
  company: "Home"
  license: Internal
  min_ansible_version: 2.9
  platforms:
    - name: Ubuntu
      versions:
        - bionic
