---
- name: "host-qemu-storage: Directory for the storage pools (on {{ vmhost_storage_path }})"
  file:
    state: directory
    path: "{{ vmhost_storage_path }}/{{ item }}"
    owner: "libvirt-qemu"
    group: "kvm"
    mode: "0770"
  loop: "{{ vmhost_storage_pools }}"

- name: "host-qemu-storage: Define the storage pools (on {{ vmhost_storage_path }})"
  virt_pool:
    command: define
    name: "{{ item }}"
    xml: "{{ lookup('template', 'storage.xml.j2') }}"
  loop: "{{ vmhost_storage_pools }}"

- name: "host-qemu-storage: Activate the storage pools"
  virt_pool:
    state: active
    name: "{{ item }}"
  loop: "{{ vmhost_storage_pools }}"

- name: "host-qemu-storage: Set the storage pools to autostart"
  virt_pool:
    name: "{{ item }}"
    autostart: yes
  loop: "{{ vmhost_storage_pools }}"

- name: "host-qemu-storage: Set the security driver to 'none' in qemu"
  lineinfile:
    path: '/etc/libvirt/qemu.conf'
    insertafter: '#security_driver = "selinux"'
    line: 'security_driver = "none"'
  notify: 'Restart libvirt-bin'
