---
- name: "Host-networking-setup: Setup IP Forwarding"
  ansible.posix.sysctl:
    state: present
    name: "net.ipv4.ip_forward"
    value: "1"
    sysctl_set: true
    reload: true

- name: "Host-networking-setup: Setup host interfaces"
  ansible.builtin.template:
    src: "01-netcfg.yaml.j2"
    dest: "/etc/netplan/01-netcfg.yaml"
    mode: '0644'
