---
- name: "Host-installation: QEMU specific Package Installation"
  ansible.builtin.package:
    name: "{{ base_vmhost_packages }}"
    state: 'present'

- name: "Host-installation: Reset facts (after libvirt installation, for network bridge)"
  ansible.builtin.setup:
    gather_subset: all
