- name: "host-installation: QEMU specific Package Installation"
  package:
    name: "{{ vmhost_packages }}"
    state: 'present'

- name: "host-installation: Reset facts (after libvirt installation, for network bridge)"
  setup:
    gather_subset: all
