- name: "host-installation: Base Package Installation"
  package:
    state: "{{ item.state | default ('present') }}"
    name: "{{ item.name }}"
  loop: "{{ base_packages }}"

- name: "host-installation: QEMU specific Package Installation"
  package:
    state: "{{ item.state | default ('present') }}"
    name: "{{ item.name }}"
  loop: "{{ vmhost_packages }}"

- name: "host-installation: Reset facts (after libvirt installation, for network bridge)"
  setup:
    gather_subset: all
