---
- name: "Host-qemu-storage: Directory for the storage pools (on {{ vmhost_storage_path }})"
  ansible.builtin.file:
    state: directory
    path: "{{ vmhost_storage_path }}/{{ item }}"
    owner: "libvirt-qemu"
    group: "kvm"
    mode: "0770"
  loop: "{{ base_vmhost_storage_pools }}"

- name: "Host-qemu-storage: Define the storage pools (on {{ vmhost_storage_path }})"
  community.libvirt.virt_pool:
    command: define
    name: "{{ item }}"
    xml: "{{ lookup('template', 'storage.xml.j2') }}"
  loop: "{{ base_vmhost_storage_pools }}"

- name: "Host-qemu-storage: Activate the storage pools"
  community.libvirt.virt_pool:
    state: active
    name: "{{ item }}"
  loop: "{{ base_vmhost_storage_pools }}"

- name: "Host-qemu-storage: Set the storage pools to autostart"
  community.libvirt.virt_pool:
    name: "{{ item }}"
    autostart: true
  loop: "{{ base_vmhost_storage_pools }}"

- name: "Host-qemu-storage: Set the security driver to 'none' in qemu"
  ansible.builtin.lineinfile:
    path: '/etc/libvirt/qemu.conf'
    insertafter: '#security_driver = "selinux"'
    line: 'security_driver = "none"'
  notify: 'Restart libvirtd'
