---
- name: "Main: Installation"
  ansible.builtin.import_tasks: "host-installation.yml"

- name: "Main: Setup the host networking"
  ansible.builtin.import_tasks: "host-networking-setup.yml"

- name: "Main: Setup the storage location for qemu"
  ansible.builtin.import_tasks: "host-qemu-storage.yml"
