- name: "main: Installation"
  import_tasks: "host-installation.yml"

- name: "main: Setup the host networking"
  import_tasks: "host-networking-setup.yml"

- name: "main: Open up the LUKS devices"
  import_tasks: "host-luks-storage.yml"

- name: "main: Import the zpool if not already there"
  import_tasks: "host-zpool-storage.yml"

- name: "main: Setup the storage location for qemu"
  import_tasks: "host-qemu-storage.yml"
