---
nextcloud_packages:
  - apache2
  - libapache2-mod-php7.2
  - php7.2-gd
  - php7.2-json
  - php7.2-mysql
  - php7.2-curl
  - php7.2-mbstring
  - php7.2-intl
  - php-imagick
  - php7.2-xml
  - php7.2-zip
  - php-apcu
  - php-imap
  - php-imagick
  - php-redis
  - unzip
  - bzip2
  - python-netaddr

php_apache_opcache:
  - regexp: 'opcache.enable=0'
    line: 'opcache.enable=1'
  - regexp: 'opcache.enable_cli'
    line: 'opcache.enable_cli=1'
  - regexp: 'opcache.interned_strings_buffer'
    line: 'opcache.interned_strings_buffer=8'
  - regexp: 'opcache.max_accelerated_files'
    line: 'opcache.max_accelerated_files=10000'
  - regexp: 'opcache.memory_consumption'
    line: 'opcache.memory_consumption=128'
  - regexp: 'opcache.save_comments'
    line: 'opcache.save_comments=1'
  - regexp: 'opcache.revalidate_freq'
    line: 'opcache.revalidate_freq=1'

apache_modules:
  - rewrite
  - headers
  - env
  - dir
  - mime
