---
nextcloud_packages:
  - apache2
  - bzip2
  - ffmpeg
  - libreoffice
  - libxml2
  - libxml2-dev
  - php7.4
  - php7.4-xml
  - php7.4-apcu
  - php7.4-bcmath
  - php7.4-bz2
  - php7.4-common
  - php7.4-curl
  - php-dompdf
  - php7.4-gd
  - php7.4-gmp
  - php7.4-imagick
  - php7.4-imap
  - php7.4-intl
  - php7.4-json
  - php-json-schema
  - php7.4-mbstring
  - php7.4-memcached
  - php7.4-mysql
  - php7.4-redis
  - php-services-json
  - php-smbclient
  - php-symfony-polyfill-iconv
  - php7.4-zip
  - unzip

php_apache_opcache:
  - regexp: 'opcache.enable=0'
    line: 'opcache.enable=1'
  - regexp: 'opcache.enable_cli'
    line: 'opcache.enable_cli=1'
  - regexp: 'opcache.interned_strings_buffer'
    line: 'opcache.interned_strings_buffer=8'
  - regexp: 'opcache.max_accelerated_files'
    line: 'opcache.max_accelerated_files=10000'
  - regexp: 'opcache.memory_consumption'
    line: 'opcache.memory_consumption=128'
  - regexp: 'opcache.save_comments'
    line: 'opcache.save_comments=1'
  - regexp: 'opcache.revalidate_freq'
    line: 'opcache.revalidate_freq=1'

apache_modules:
  - rewrite
  - headers
  - env
  - dir
  - mime
  - remoteip
  - ssl
