---
nextcloud_packages:
  - apache2
  - libapache2-mod-php7.2
  - php7.2-gd
  - php7.2-json
  - php7.2-mysql
  - php7.2-curl
  - php7.2-mbstring
  - php7.2-intl
  - php-imagick
  - php7.2-xml
  - php7.2-zip
