---
- name: 'Install-grafana: Import GPG key'
  ansible.builtin.apt_key:
    url: "https://apt.grafana.com/gpg.key"
    state: 'present'

- name: 'Install-grafana: Add grafana repository'
  ansible.builtin.apt_repository:
    repo: 'deb https://apt.grafana.com stable main'
    state: 'present'
    update_cache: true

- name: 'Install-grafana: Install grafana'
  ansible.builtin.package:
    name: "grafana"
    state: 'present'
