---
- name: 'install-grafana: Import GPG key'
  apt_key:
    url: "https://packages.grafana.com/gpg.key"
    state: 'present'

- name: 'install-grafana: Add grafana repository'
  apt_repository:
    repo: 'deb https://packages.grafana.com/oss/deb stable main'
    state: 'present'
    update_cache: true

- name: 'install-grafana: Install grafana'
  package:
    name: "grafana={{ grafana_version }}"
    state: 'present'
