---
- name: 'Install-grafana: Add Grafana APT repository'
  ansible.builtin.deb822_repository:
    name: 'grafana'
    types:
      - 'deb'
    uris: 'https://apt.grafana.com'
    suites:
      - 'stable'
    components:
      - 'main'
    signed_by: 'https://apt.grafana.com/gpg-full.key'
    state: 'present'

- name: 'Install-grafana: Install grafana'
  ansible.builtin.package:
    name: "grafana"
    state: 'present'
    update_cache: yes
