---
- name: 'main: Setup dependencies'
  import_tasks: 'pre-setup.yml'

- name: 'main: Install main grafana package'
  import_tasks: 'install-grafana.yml'

- name: 'main: Configure grafana'
  import_tasks: 'setup-grafana.yml'
