---
- name: 'Main: Setup dependencies'
  ansible.builtin.import_tasks: 'pre-setup.yml'

- name: 'Main: Install main grafana package'
  ansible.builtin.import_tasks: 'install-grafana.yml'

- name: 'Main: Configure grafana'
  ansible.builtin.import_tasks: 'setup-grafana.yml'
