---
- name: "Setup-guitar-tab-trainer: Log in to ghcr.io"
  community.docker.docker_login:
    registry_url: "ghcr.io"
    username: "{{ services_guitar_tab_trainer_ghcr_username }}"
    password: "{{ services_guitar_tab_trainer_ghcr_password }}"
  when: services_guitar_tab_trainer_ghcr_login_enabled | bool

- name: "Setup-guitar-tab-trainer: Copy over the docker-compose.yml"
  ansible.builtin.template:
    src: "opt_guitar_tab_trainer_docker-compose.yml.j2"
    dest: "{{ services_guitar_tab_trainer_compose_project_dir }}/docker-compose.yml"
    mode: '0644'

- name: "Setup-guitar-tab-trainer: Run the guitar-tab-trainer stack"
  community.docker.docker_compose_v2:
    project_src: "{{ services_guitar_tab_trainer_compose_project_dir }}"
    state: "present"
    pull: "always"

