---
- name: 'Main: Setup certbot base'
  ansible.builtin.import_tasks: 'setup-certbot-structure.yml'

- name: 'Main: Push the certificates'
  ansible.builtin.import_tasks: 'setup-certificates.yml'

- name: 'Main: Create the accounts'
  ansible.builtin.import_tasks: 'setup-accounts.yml'
