---
- name: 'Install-mysql: Install the mariadb package'
  ansible.builtin.apt:
    name: 'default-mysql-server'
    state: present

- name: 'Install-mysql: Send my.cnf over'
  ansible.builtin.template:
    src: my.cnf.j2
    dest: '/etc/mysql/mysql.cnf'
    owner: root
    group: root
    mode: '0644'
  notify: 'Restart mysql'

- name: 'Install-mysql: Ansible needs a root/.my.cnf file. Fiiiiiiine'
  ansible.builtin.template:
    src: 'root_my.cnf.j2'
    dest: "/root/.my.cnf"
    owner: 'root'
    group: 'root'
    mode: '0600'
  no_log: true

- name: 'Install-mysql: Setup root account.'
  community.mysql.mysql_user:
    name: "{{ mysql_root_user }}"
    password: "{{ mysql_root_pass }}"
  no_log: true
