---
- name: 'main: Setup the groups as needed'
  import_tasks: 'setup-groups.yml'

- name: 'main: Setup the users as needed'
  import_tasks: 'setup-users.yml'

- name: 'main: Setup sudo as needed'
  import_tasks: 'setup-sudo.yml'
