---
- name: 'Main: Setup local DNS'
  ansible.builtin.import_tasks: 'setup-hosts-file.yml'

- name: 'Main: Setup networking'
  ansible.builtin.import_tasks: 'setup-networking.yml'

- name: 'Main: Install the common packages all boxes need.'
  ansible.builtin.import_tasks: 'pre-setup.yml'

- name: 'Main: Setup timezone'
  ansible.builtin.import_tasks: 'setup-timezone.yml'

- name: 'Main: Setup the groups as needed'
  ansible.builtin.import_tasks: 'setup-groups.yml'

- name: 'Main: Setup the users as needed'
  ansible.builtin.import_tasks: 'setup-users.yml'

- name: 'Main: Setup sudo as needed'
  ansible.builtin.import_tasks: 'setup-sudo.yml'
