---
- name: 'main: Setup the groups as needed'
  import_tasks: 'setup-groups.yml'

- name: 'main: Setup the users as needed'
  import_tasks: 'setup-users.yml'

- name: 'main: Setup sudo as needed'
  import_tasks: 'setup-sudo.yml'

- name: 'main: Setup networking'
  import_tasks: 'setup-networking.yml'

- name: 'main: Setup networking'
  import_tasks: 'setup-hosts-file.yml'

- name: 'main: Setup timezone'
  import_tasks: 'setup-timezone.yml'
