---
- name: "setup-networking: Setup host interfaces"
  template:
    src: "01-netcfg.yaml.j2"
    dest: "/etc/netplan/01-netcfg.yaml"
    mode: 0644

- name: "setup-networking: Setup hostname"
  hostname:
    name: "{{ common_hostname }}"

- name: "setup-networking: Apply netplan"
  command: # noqa 301 - We don't mind if this commands executes all the time.
    cmd: warn=no /usr/sbin/netplan apply
