---
- name: 'setup-timezone: Delete current /etc/localtime'
  file:
    dest: '/etc/localtime'
    state: 'absent'

- name: 'setup-timezone: Setup the timezone to be UTC'
  file:
    src: '/usr/share/zoneinfo/Etc/UTC'
    dest: '/etc/localtime'
    state: 'link'

- name: 'setup-timezone: Restart rsyslog'
  service:
    name: 'rsyslog'
    state: 'restarted'
