---
- name: 'Setup-timezone: Delete current /etc/localtime'
  ansible.builtin.file:
    dest: '/etc/localtime'
    state: 'absent'

- name: 'Setup-timezone: Setup the timezone to be UTC'
  ansible.builtin.file:
    src: '/usr/share/zoneinfo/Etc/UTC'
    dest: '/etc/localtime'
    state: 'link'

- name: 'Setup-timezone: Restart rsyslog'
  ansible.builtin.service:
    name: 'rsyslog'
    state: 'restarted'
