---
- name: 'Setup-sudo: Push sudoers under /etc/sudoers.d'
  ansible.builtin.copy:
    src: 'files/etc_sudoers_d_91_common'
    dest: '/etc/sudoers.d/91-common-role-users'
    mode: '0440'
    owner: 'root'
