---
- name: 'Setup-groups: Setup all groups as needed.'
  ansible.builtin.group:
    name: "{{ group.name }}"
    gid: "{{ group.gid }}"
  loop: "{{ all_groups }}"
  loop_control:
    loop_var: "group"
  no_log: true
