---
- name: "Setup-networking: Setup host interfaces"
  ansible.builtin.template:
    src: "01-netcfg.yaml.j2"
    dest: "/etc/netplan/01-netcfg.yaml"
    mode: '0644'

- name: "Setup-networking: Setup hostname"
  ansible.builtin.hostname:
    name: "{{ common_hostname }}"

- name: "Setup-networking: Apply netplan"
  ansible.builtin.command: # noqa no-changed-when - We don't mind if this commands executes all the time.
    cmd: /usr/sbin/netplan apply
