---
- name: 'Setup-users: Setup all users as needed.'
  ansible.builtin.user:
    user: "{{ user.uname }}"
    uid: "{{ user.uid }}"
    group: "{{ user.group }}"
    comment: "{{ user.name }}"
    shell: "{{ user.shell | default('/bin/bash') }}"
  loop: "{{ all_users }}"
  loop_control:
    loop_var: "user"
  no_log: true

- name: "Setup-users: Add the public key for each user."
  ansible.posix.authorized_key:
    user: "{{ user.uname }}"
    key: "{{ user.ssh_key }}"
  loop: "{{ all_users }}"
  loop_control:
    loop_var: "user"
  no_log: true

- name: "Setup-users: Remove sudoers file no longer needed."
  ansible.builtin.file:
    path: '/etc/sudoers.d/90-cloud-init-users'
    state: 'absent'

- name: 'Setup-users: Remove packer user.'
  ansible.builtin.user:
    user: 'packer'
    state: 'absent'
    remove: false

- name: 'Setup-users: Delete packer directory (owned by root) CICD-42'
  ansible.builtin.file:
    path: '/home/packer'
    state: 'absent'
