---
- name: 'setup-users: Setup all users as needed.'
  user:
    name: "{{ user.uname }}"
    uid: "{{ user.uid }}"
    group: "{{ user.group }}"
    comment: "{{ user.name }}"
    shell: "{{ user.shell | default('/bin/bash') }}"
  loop: "{{ all_users }}"
  loop_control:
    loop_var: "user"

- name: "setup-users: Add the public key for each user."
  authorized_key:
    user: "{{ user.uname }}"
    key: "{{ user.ssh_key }}"
  loop: "{{ all_users }}"
  loop_control:
    loop_var: "user"

- name: "setup-users: Remove sudoers file no longer needed."
  file:
    path: '/etc/sudoers.d/90-cloud-init-users'
    state: 'absent'

- name: 'setup-users: Remove packer user.'
  user:
    name: 'packer'
    state: 'absent'
    remove: no

- name: 'setup-users: Delete packer directory (owned by root) CICD-42'
  file:
    path: '/home/packer'
    state: 'absent'
