---
- name: 'Clean-up-before-reboot: Remove machine-id so it is unique.'
  ansible.builtin.copy:
    content: ''
    dest: /etc/machine-id
    force: false
    group: 'sys'
    owner: 'root'
    mode: '0555'

- name: 'Clean-up-before-reboot: Delete existing file of machine-id'
  ansible.builtin.file:
    path: '/var/lib/dbus/machine-id'
    state: absent

- name: 'Clean-up-before-reboot: Link this to the empty file.'
  ansible.builtin.file:
    src: '/etc/machine-id'
    dest: '/var/lib/dbus/machine-id'
    state: link
