---
# TODO: Find a different user to use as an automation one. This
#       is replicated from the roles/base/common role.
- name: "Clean-up-users: This is replicated from the common role. - michnmi"
  ansible.builtin.user:
    user: "michnmi"
    uid: "1000"
    group: "sudo"

# Adding the noqa here but hopefully we'll be able to get out of this setup soon enough.
- name: "Clean-up-users: This is replicated from the common role. - michnmi"
  ansible.posix.authorized_key:
    user: "michnmi"
    key: "ecdsa-sha2-nistp521 AAAAE2VjZHNhLXNoYTItbmlzdHA1MjEAAAAIbmlzdHA1MjEAAACFBAAfhGGiiPbkUrLYQtHTtoDBAsvCWVdxErmqeBUH2RWPpaQa15s8tRWabUHf5rosLja1O3YBAuhVjja6ndBeTf6dTQA5Icg435/FE2n9Me//Glqvde0jJNitoJlc+yV77wMLK1m2dmXUJxWy+tkI/oku/O75BWcgr1Po3HrkSbq1uSUIkA== \necdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBIJXg6YhfPQr6U164LNcafHBcDKEQ7VslUgvopx7/Z0QtV6XYjxblUjXhzns4j42NbQcW68rTRUxZnqPE3K2qFI= michnmi@W2WY2VR9Y1 \nssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDPX2oTY+e2B+E3CsK/9+0/Sli7bH3MppcMlsR3f/5iOr3YfcejVQDu+9MiMtnX5CA3qRNGEqW971kiPrxqQswMO2Zph/fhDWHZO4Wyh1AFRSuIavFFUCrg3pIYGCoNZ0KausSDB9sjp5tVNJEJlQLGiTs/NCuh1Lr7BlPWkRm2uoK7SooBHRCbvbJOVEadDXVXScZfdkFoqsnGymxN3f60TFtXM+NJ6p9n1mWGIMnjkec/hA/EUPFJsqjOhUp+nT8GnprIlImt/pPwe/9by3e9/+1vmUQm3kl+z/eIwcZs1HWazDIWdd/Zciw/XzTy53JuGPm3T+FBevE07p3d3z0z home_uk" # noqa 204

- name: "Clean-up-users: This is replicated from the common role. - automation (group)"
  ansible.builtin.group:
    name: "automation"
    gid: "5000"

- name: "Clean-up-users: This is replicated from the common role. - jenkins_automation"
  ansible.builtin.user:
    user: "jenkins_automation"
    uid: "5001"
    group: "automation"

- name: "Clean-up-users: This is replicated from the common role. - jenkins_automation"
  ansible.posix.authorized_key:
    user: "jenkins_automation"
    key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEMP68U00kNcTtf3UWM6UYk97UjOMrPXhsu1jqlxgYc5 jenkins_automation CICD-42" # noqa 204

- name: "Clean-up-users: This is replicated from the common role. - sudoers"
  ansible.builtin.copy:
    src: "files/etc_sudoers_d_91_common"
    dest: "/etc/sudoers.d/91-common-role-users"
    mode: "0440"
    owner: "root"

- name: "Clean-up-users: Setup a password for root. Only accessible through console"
  ansible.builtin.user:
    user: "root"
    password: "{{ root_password }}"

- name: "Clean-up-users: Delete users we do not want"
  ansible.builtin.debug:
    msg: "Pass: Nothing defined so far"
