---
- name: 'disable-services: Make sure no automatic updates are configured in apt'
  copy:
    src: 'files/etc_apt_apt.conf.d_10periodic'
    dest: '/etc/apt/apt.conf.d/10periodic'

- name: 'disable-services: Make sure no automatic updates are configured in apt - try 2'
  copy:
    src: 'files/etc_apt_apt.conf.d_51-disable-unattended-upgrades'
    dest: '/etc/apt/apt.conf.d/51-disable-unattended-upgrades'

- name: 'disable-services: Make sure they are disabled when machine-id is reset for Nomad'
  copy:
    src: 'files/lib_systemd_system-preset_10-disable-unattended-upgrades'
    dest: '/lib/systemd/system-preset/10-disable-unattended-upgrades'

- name: 'disable-services: Making sure all apt timers are never started'
  systemd:
    name: "{{ item.name }}"
    enabled: no
    masked: yes
    state: stopped
    daemon_reload: yes
  loop: "{{ cloud_vm_disabled_services }}"

# This is happening on a cloud vm of ubuntu. It will always have swap.
- name: 'disable-services: Making sure swap is turned off.'
  command: swapoff -a # noqa 301

- name: 'disable-services: Making sure no swap mountpoints exist.'
  lineinfile:
    path: /etc/fstab
    regexp: '\ swap\ '
    state: absent
