---
- name: "Initial-dhcp-setup: Set default interface name"
  ansible.builtin.set_fact:
    net_interface: "ens3" # default to the interface name for Ubuntu 18.04
  when: ansible_distribution_version is version('18.04', '=')

- name: "Initial-dhcp-setup: Update the name if we're in Ubuntu 22.04"
  ansible.builtin.set_fact:
    net_interface: "enp0s3" # interface name for Ubuntu 22.04
  when: ansible_distribution_version is version('22.04', '=')

- name: "Initial-dhcp-setup: Remove cloud-init networking"
  ansible.builtin.file:
    dest: "/etc/netplan/50-cloud-init.yaml"
    state: absent

- name: "Initial-dhcp-setup: Setup initial dhcp"
  ansible.builtin.template:
    src: templates/etc_netplan_01-netcfg.yaml.j2
    dest: /etc/netplan/01-netcfg.yaml
    owner: root
    mode: '0644'
