---
- name: 'Main: Disable services that are not needed'
  ansible.builtin.include_tasks: 'disable-services.yml'
- name: 'Main: Destroy users that are not needed'
  ansible.builtin.include_tasks: 'clean-up-users.yml'
- name: 'Main: Fix initial DHCP of cloud-vm'
  ansible.builtin.include_tasks: 'initial-dhcp-setup.yml'
- name: 'Main: Clean up before the reboot'
  ansible.builtin.include_tasks: 'clean-up-before-reboot.yml'
