---
- name: 'packer-installation: Download packer from the website'
  ansible.builtin.unarchive:
    src: "{{ services_packer_base_url }}/{{ services_packer_version }}/packer_{{ services_packer_version }}_{{ services_packer_arch }}.zip"
    dest: '/usr/local/bin'
    remote_src: true
    mode: '0655'

# A better way will be to move from json to HCL2 and use https://developer.hashicorp.com/packer/integrations/hashicorp/qemu#installation
- name: 'packer-installation: Setup qemu plugin'
  ansible.builtin.command:
    argv:
      - "/usr/local/bin/packer"
      - "plugins"
      - "install"
      - "github.com/hashicorp/qemu"
    creates: "/var/lib/jenkins/.config/packer/plugins/github.com/hashicorp/qemu/packer-plugin-qemu_v1.0.10_x5.0_linux_amd64"
  become: true
  become_user: jenkins # noqa partial-become
