---
- name: 'pre-setup: Packer host specific packages'
  package:
    name: "{{ packer_packages }}"
    state: 'present'

- name: 'pre-setup: Create a packer user that has access to kvm'
  user:
    name: "{{ packer_user }}"
    groups: "kvm"
    append: true

- name: 'pre-setup: Create the location for images'
  file:
    path: "{{ packer_file_location }}"
    state: directory
    owner: "{{ packer_user }}"
    mode: '0750'
