---
- name: 'pre-requirements: Base Package Installation - using apt to use apt-get update'
  apt:
    state: "{{ item.state | default ('present') }}"
    name: "{{ item.name }}"
    update_cache: yes
  loop: "{{ base_packages }}"

- name: 'pre-requirements: Packer host specific packages'
  package:
    state: "{{ item.state | default ('present') }}"
    name: "{{ item.name }}"
  loop: "{{ packer_packages }}"
