---
galaxy_info:
  role_name: "prometheus"
  author: "Michalis Michaloliakos <michalis.michaloliakos@gmail.com>"
  description: "Allowing a host to run a prometheus server"
  company: "Home"
  license: Internal
  min_ansible_version: 2.9
  platforms:
    - name: Ubuntu
      versions:
        - bionic
