---
galaxy_info:
  role_name: "komga"
  author: "Michalis Michaloliakos <michalis.michaloliakos@gmail.com>"
  description: "Setting up a host to act as a komga host."
  company: "Home"
  license: Internal
  min_ansible_version: "2.9"
  platforms:
    - name: Ubuntu
      versions:
        - bionic
