---
- name: 'Main: Prepare host'
  ansible.builtin.import_tasks: 'pre-setup.yml'

- name: 'Main: Allow jenkins to run ansible commands'
  ansible.builtin.import_tasks: 'setup-ansible.yml'

- name: 'Main: Allow jenkins to run terraform commands'
  ansible.builtin.import_tasks: 'setup-terraform.yml'

- name: 'Main: Setup Jenkins'
  ansible.builtin.import_tasks: 'setup-jenkins.yml'
