---
- name: 'main: Prepare host'
  import_tasks: 'pre-setup.yml'

- name: 'main: Allow jenkins to run ansible commands'
  import_tasks: 'setup-ansible.yml'

- name: 'main: Allow jenkins to run terraform commands'
  import_tasks: 'setup-terraform.yml'

- name: 'main: Setup Jenkins'
  import_tasks: 'setup-jenkins.yml'
