---
- name: "Setup-ansible: Install ansible."
  ansible.builtin.pip:
    name: "ansible==2.10.7"
    state: "present"
    executable: "pip3"
  environment:
    LANG: "en_US.UTF-8"
    LC_ALL: "en_US.UTF-8"

- name: "Setup-ansible: Install ansible-lint."
  ansible.builtin.pip:
    name: "ansible-lint"
    state: "present"
    executable: "pip3"
