---
- name: "setup-ansible: Install ansible."
  pip:
    name: "ansible"
    state: "present"
    executable: "pip3"

- name: "setup-ansible: Install ansible-lint."
  pip:
    name: "ansible-lint"
    state: "present"
    executable: "pip3"
