---
- name: 'pre-setup: Setup terraform commands'
  unarchive:
    src: 'https://releases.hashicorp.com/terraform/0.13.3/terraform_0.13.3_linux_amd64.zip'
    dest: /usr/local/bin
    remote_src: yes
    mode: 0655
