---
# CICD-63: Changed this to apt ansible-lint as ansible is installed with custom build.
- name: 'setup-ansible: Setup ansible-lint'
  apt:
    name: "ansible-lint"
    state: 'present'
    update_cache: true
