---
- name: "Setup-ansible: Install ansible."
  ansible.builtin.pip:
    name: "ansible==2.10.7"
    state: "present"
    executable: "pip3"
  environment:
    LANG: "en_US.UTF-8"
    LC_ALL: "en_US.UTF-8"

- name: "Setup-ansible: Install ansible-lint."
  ansible.builtin.pip:
    name: "ansible-lint"
    state: "present"
    executable: "pip3"

- name: "Setup-ansible: Ensure /etc/ansible exists"
  ansible.builtin.file:
    path: "/etc/ansible"
    state: "directory"
    mode: '0755'

- name: "Setup-ansible: Copy over the ansible-galaxy requirements file"
  ansible.builtin.copy:
    src: "requirements.yml"
    dest: "/etc/ansible/requirements.yml"
    mode: '0644'

- name: "Setup-ansible: Install ansible-galaxy collections"
  ansible.builtin.command: >-
    ansible-galaxy collection install -r /etc/ansible/requirements.yml
    -p /usr/share/ansible/collections
  register: services_jenkins_galaxy_collections
  changed_when: "'Nothing to do' not in services_jenkins_galaxy_collections.stdout"
