---
- name: 'pre-setup: Download and untar the node_exporter archive'
  unarchive:
    src: 'https://github.com/prometheus/node_exporter/releases/download/v1.0.1/node_exporter-1.0.1.linux-amd64.tar.gz'
    dest: '/usr/bin'
    mode: 0755
    owner: 'root'
    group: 'root'
    remote_src: 'yes'
    extra_opts:
      - '--strip-components=1'
      - 'node_exporter-1.0.1.linux-amd64/node_exporter'
