---
- name: 'Pre-setup: Create the node_exporter group'
  ansible.builtin.group:
    name: "{{ base_node_exporter_group }}"
    state: present
    system: true

- name: 'Pre-setup: Create the node_exporter user'
  ansible.builtin.user:
    user: "{{ base_node_exporter_user }}"
    groups:
      - "{{ base_node_exporter_group }}"
    append: true
    shell: /usr/sbin/nologin
    system: true
    create_home: false
    home: '/'
