---
- name: 'Configure-apache: Enable APC for php'
  ansible.builtin.lineinfile:
    dest: /etc/php/8.2/cli/php.ini
    line: "apc.enable_cli = 1"
    insertbefore: "^; End:$"
    state: present

- name: 'Configure-apache: Enable PHP OPcache for php.ini'
  ansible.builtin.lineinfile:
    dest: /etc/php/8.2/apache2/php.ini
    regexp: "{{ opcache_line.regexp }}"
    line: "{{ opcache_line.line }}"
    state: present
    backrefs: yes
  loop: "{{ services_php_apache_opcache }}"
  loop_control:
    loop_var: "opcache_line"
  notify: 'Reload Apache'

- name: 'Configure-apache: Enable PHP other options for php.ini'
  ansible.builtin.lineinfile:
    dest: /etc/php/8.2/apache2/php.ini
    regexp: "^{{ php_option.option }}"
    line: "{{ php_option.option }} = {{ php_option.value }}"
  loop: "{{ php_ini_options }}"
  loop_control:
    loop_var: "php_option"
  notify: 'Reload Apache'

- name: 'Configure-apache: Enable related apache2 modules'
  community.general.apache2_module:
    name: "{{ item }}"
    state: present
  loop: "{{ services_apache_modules }}"
  notify: 'Restart Apache'

- name: 'Configure-apache: Disable default conf in apache'
  ansible.builtin.file:
    path: '/etc/apache2/sites-enabled/000-default.conf'
    state: absent
  notify: 'Reload Apache'

- name: 'Configure-apache: Setup the nextcloud conf in apache'
  ansible.builtin.template:
    src: 'etc_apache2_sites-available_nextcloud.conf.j2'
    dest: '/etc/apache2/sites-available/nextcloud.conf'
    mode: '0644'
  notify: 'Reload Apache'

- name: 'Configure-apache: Setup the ssl conf in apache'
  ansible.builtin.template:
    src: 'etc_apache2_sites-available_default-ssl.conf.j2'
    dest: '/etc/apache2/sites-available/default-ssl.conf'
    mode: '0644'
  notify: 'Reload Apache'

- name: 'Configure-apache: Enable nextcloud conf in apache'
  ansible.builtin.file:
    path: '/etc/apache2/sites-enabled/nextcloud.conf'
    src: '/etc/apache2/sites-available/nextcloud.conf'
    state: link
  notify: 'Reload Apache'

- name: 'Configure-apache: Enable ssl conf in apache'
  ansible.builtin.file:
    path: '/etc/apache2/sites-enabled/default-ssl.conf'
    src: '/etc/apache2/sites-available/default-ssl.conf'
    state: link
  notify: 'Reload Apache'
