---
- name: 'Main: Install dependencies'
  ansible.builtin.import_tasks: 'pre-setup.yml'

- name: 'Main: Install nextcloud'
  ansible.builtin.import_tasks: 'configure-apache.yml'

- name: 'Main: Install nextcloud'
  ansible.builtin.import_tasks: 'install-nextcloud.yml'

- name: 'Main: Setup Database backup.'
  ansible.builtin.import_tasks: 'setup-mysql-backup.yml'

- name: 'Main: Migrate existing installation'
  ansible.builtin.import_tasks: 'migrate-nextcloud.yml'
  when: services_nextcloud_migrate
