---
- name: 'main: Install dependencies'
  import_tasks: 'pre-setup.yml'

- name: 'main: Install nextcloud'
  import_tasks: 'configure-apache.yml'

- name: 'main: Install nextcloud'
  import_tasks: 'install-nextcloud.yml'

- name: 'main: Setup Database backup.'
  import_tasks: 'setup-mysql-backup.yml'

- name: 'main: Migrate existing installation'
  import_tasks: 'migrate-nextcloud.yml'
  when: nextcloud_migrate
