---
- name: 'migrate-nextcloud: Setup the database.'
  mysql_db:
    name: nextcloud
    state: import
    target: "{{ nextcloud_migrate_database_path }}/{{nextcloud_migrate_database_file }}"
  notify: 'Reload Apache'

- name: 'migrate-nextcloud: Destroy the existing data directory.'
  file:
    path: "{{ nextcloud_data_dir }}"
    state: absent
  notify: 'Reload Apache'

- name: 'migrate-nextcloud: Create a link to the migrated data directory.'
  file:
    src: "{{ nextcloud_migrate_datadir_path }}"
    dest: "{{ nextcloud_data_dir }}"
    state: link
  notify: 'Reload Apache'
