---
- name: 'Pre-setup: CICD-76/STOR-82 - add repository for php8.2'
  ansible.builtin.pt_repository:
    repo: 'ppa:ondrej/php'
    state: 'present'
    mode: '0644'
    update_cache: true

- name: 'Pre-setup: Install required packages'
  ansible.builtin.apt:
    name: "{{ services_nextcloud_packages }}"
    state: 'present'
    update_cache: true

- name: 'Pre-setup: Setup php 8.2 as php'
  ansible.builtin.file:
    src: "/usr/bin/php8.2"
    dest: "/etc/alternatives/php"
    state: 'link'

- name: 'Pre-setup: Setup nextcloud user in mysql.'
  community.mysql.mysql_user:
    name: "{{ services_nextcloud_db_user }}"
    password: "{{ services_nextcloud_db_pass }}"
  no_log: true
