---
- name: 'pre-setup: Install required packages'
  apt:
    name: "{{ nextcloud_packages }}"
    state: 'present'
    update_cache: true

- name: 'pre-setup: Setup nextcloud user in mysql.'
  mysql_user:
    name: "{{ nextcloud_db_user }}"
    password: "{{ nextcloud_db_pass }}"
  no_log: true
