---
- name: "setup-forwarder: Create Splunk group"
  group:
    name: "{{ splunkforwarder_user }}"
    gid: 5997
    state: present

- name: "setup-forwarder: Create Splunk user"
  user:
    name: "{{ splunkforwarder_user }}"
    group: "{{ splunkforwarder_user }}"
    uid: 5997
    state: present

- name: "setup-forwarder: Untar the splunk package"
  unarchive:
    remote_src: true
    src: "/tmp/splunkforwarder-9.2.0.1-d8ae995bf219-Linux-x86_64.tgz"
    dest: /opt/
    owner: "{{ splunkforwarder_user }}"
    group: "{{ splunkforwarder_user }}"

- name: "setup-forwarder: Setup user credentials"
  template:
    src: "templates/user-seed.conf.j2"
    dest: "/opt/splunkforwarder/etc/system/local/user-seed.conf"
    owner: "{{ splunkforwarder_user }}"
    group: "{{ splunkforwarder_user }}"
    mode: 0400
    remote_src: false

- name: "setup-forwarder: Setup inputs"
  template:
    src: templates/inputs.conf.j2
    dest: /opt/splunkforwarder/etc/system/local/inputs.conf
    owner: "{{ splunkforwarder_user }}"
    group: "{{ splunkforwarder_user }}"
    mode: 0400
    remote_src: false

- name: "setup-forwarder: Set logfile permissions"
  acl:
    path: "{{ item }}"
    entity: "{{ splunkforwarder_user }}"
    state: present
    etype: user
    permissions: r
    recursive: true
  become: true
  with_items: "{{ splunkforwarder_logs }}"

- name: "setup-forwarder: Setup outputs"
  ansible.builtin.template:
    src: templates/outputs.conf.j2
    dest: /opt/splunkforwarder/etc/system/local/outputs.conf
    owner: "{{ splunkforwarder_user }}"
    group: "{{ splunkforwarder_user }}"
    mode: 0400
    remote_src: false

- name: "setup-forwarder: Setup systemd file"
  template:
    src: SplunkForwarder.service.j2
    dest: /etc/systemd/system/SplunkForwarder.service
    owner: root
    group: root
    mode: 0644

- name: "setup-forwarder: Enable systemd file"
  service:
    name: SplunkForwarder
    enabled: true
    state: started
    daemon_reload: true
