---
- name: "Setup nextcloud"
  hosts: storage_services
  become: true
  become_method: sudo
  roles:
    - common
    - node_exporter
    - mysql
    - nfs_client
    - nextcloud
    - splunk_forwarder
