---
- name: "Setup nextcloud"
  hosts: storage_services
  become: yes
  become_method: sudo
  roles:
    - common
    - node_exporter
    - splunk_forwarder
    - mysql
    - nfs_client
    - nextcloud
