---
- name: "Setup nginx as a reverseproxy"
  hosts: network_proxies
  become: true
  become_method: sudo
  roles:
    - common
    - node_exporter
    - splunk_forwarder
    - certbot
    - nginx_reverseproxy
