---
- name: "Setup splunk"
  hosts: splunk
  become: true
  become_method: sudo
  roles:
    - common
    - node_exporter
    - nfs_client
    # Cannot do splunk unless we have splunk_backend again (See STOR-96)
    # - splunk 
