---
- name: "Setup YouTrack host"
  hosts: youtrack
  become: true
  become_method: sudo
  roles:
    - common
    - node_exporter
    - virtiofs_client
    - docker_host
    - youtrack
    - splunk_forwarder
