---
services_packer_base_url: 'https://releases.hashicorp.com/packer'
services_packer_version: '1.10.1'
services_packer_arch: 'linux_amd64'
services_packer_user: 'packer'
services_packer_file_location: '/tmp/packer'
