---
- name: 'Install-emby: Install the emby-server binary.'
  ansible.builtin.apt:
    deb: '/tmp/emby-server-deb_{{ services_emby_version }}_amd64.deb'

- name: 'Install-emby: Stop the service'
  ansible.builtin.service:
    name: 'emby-server'
    state: 'stopped'

- name: 'Install-emby: Edit unit file to restart on failure'
  ansible.builtin.lineinfile:
    dest: "/usr/lib/systemd/system/emby-server.service"
    insertafter: 'RestartForceExitStatus=3'
    line: "Restart=on-failure"

- name: 'Install-emby: Clean up the binary'
  ansible.builtin.file:
    dest: '/tmp/emby-server-deb_{{ services_emby_version }}_amd64.deb'
    state: absent
