---
- name: 'main: Install dependencies'
  import_tasks: 'pre-setup.yml'

- name: 'main: Install the emby server'
  import_tasks: 'install-emby.yml'

- name: 'main: Migrate existing installation'
  import_tasks: 'migrate-emby.yml'
  when: emby_migrate

- name: 'main: Setup IPTV'
  import_tasks: 'setup-iptv.yml'
  when: setup_iptv

- name: 'main: Setup openvpn'
  import_tasks: 'openvpn-emby.yml'
