---
- name: 'Main: Install dependencies'
  ansible.builtin.import_tasks: 'pre-setup.yml'

- name: 'Main: Install the emby server'
  ansible.builtin.import_tasks: 'install-emby.yml'

- name: 'Main: Migrate existing installation'
  ansible.builtin.import_tasks: 'migrate-emby.yml'
  when: services_emby_migrate

- name: 'Main: Setup IPTV'
  ansible.builtin.import_tasks: 'setup-iptv.yml'
  when: services_setup_iptv

- name: 'Main: Setup openvpn'
  ansible.builtin.import_tasks: 'openvpn-emby.yml'
