---
- name: "Migrate-emby: Destroy current config directories"
  ansible.builtin.file:
    dest: "/var/lib/emby/{{ item }}"
    state: absent
  with_items:
    - "config"
    - "data"
    - "metadata"
    - "plugins"
    - "root"

- name: "Migrate-emby: Link the new directories"
  ansible.builtin.file:
    src: "{{ base_emby_data_dir }}/{{ item }}"
    dest: "/var/lib/emby/{{ item }}"
    state: "link"
  with_items:
    - "config"
    - "data"
    - "metadata"
    - "plugins"
    - "root"

- name: "Migrate-emby: Send over the mock certs (https)"
  ansible.builtin.unarchive:
    src: "files/certs.tgz"
    dest: "/var/lib/emby/"
    mode: '0700'
    owner: "emby"
    group: "emby"

- name: "Migrate-emby: Restart the service"
  ansible.builtin.service:
    name: "emby-server"
    state: "restarted"
    enabled: true
    daemon_reload: true
