---
- name: "migrate-emby: Destroy current config directories"
  file:
    dest: "/var/lib/emby/{{ item }}"
    state: absent
  with_items:
    - "config"
    - "data"
    - "metadata"
    - "plugins"
    - "root"

- name: "migrate-emby: Link the new directories"
  file:
    src: "{{ emby_data_dir }}/{{ item }}"
    dest: "/var/lib/emby/{{ item }}"
    state: "link"
  with_items:
    - "config"
    - "data"
    - "metadata"
    - "plugins"
    - "root"

- name: "migrate-emby: Send over the mock certs (https)"
  unarchive:
    src: "files/certs.tgz"
    dest: "/var/lib/emby/"
    mode: 0700
    owner: "emby"
    group: "emby"

- name: "migrate-emby: Restart the service"
  service:
    name: "emby-server"
    state: "restarted"
    enabled: true
    daemon_reload: yes
