---
- name: 'pre-setup: Install required packages'
  apt:
    name: "{{ emby_packages }}"
    state: 'present'
    update_cache: true

- name: 'pre-setup: Download the emby server binary'
  get_url:
    url: 'https://github.com/MediaBrowser/Emby.Releases/releases/download/4.6.7.0/emby-server-deb_4.6.7.0_amd64.deb'
    dest: '/tmp/emby-server-deb_4.6.7.0_amd64.deb'
    mode: 0600
