---
- name: "Setup-iptv: Send over the m3u file (TV Tuner)"
  ansible.builtin.copy:
    src: IPTV_original.m3u
    dest: "/var/lib/emby/IPTV_original.m3u"
    owner: "root"
    group: "automation"
    mode: '0440'

- name: "Setup-iptv: Setup the m3u parsing script in the path"
  ansible.builtin.copy:
    src: parse_m3u.py
    dest: "/usr/bin/parse_m3u"
    owner: "root"
    group: "root"
    mode: '0755'

- name: "Setup-iptv: Select the channels that we want"
  ansible.builtin.template:
    src: "templates/list_of_channels.txt.j2"
    dest: "/tmp/list_of_channels.txt"
    owner: "emby"
    group: "automation"
    mode: '0440'
    remote_src: false

- name: "Setup-iptv: Create EMBY.m3u"
  ansible.builtin.command:
    cmd: /usr/bin/parse_m3u --m3u8_file /var/lib/emby/IPTV_original.m3u --channel_names_file /tmp/list_of_channels.txt --output_format extinf --output_file /var/lib/emby/EMBY.m3u
    creates: "/var/lib/emby/EMBY.m3u"

- name: "Setup-iptv: Update permissions of EMBY.m3u"
  ansible.builtin.file:
    path: /var/lib/emby/EMBY.m3u
    owner: "emby"
    group: "automation"
    mode: '0440'

- name: "Setup-iptv: Update permissions of var/lib/emby"
  ansible.builtin.file:
    path: /var/lib/emby/
    owner: "emby"
    group: "automation"
    mode: '0750'
