---
- name: 'Main: Prepare the installation.'
  ansible.builtin.import_tasks: 'pre-setup.yml'

- name: 'Main: Prepare the installation.'
  ansible.builtin.import_tasks: 'install-prometheus.yml'

- name: 'Main: Configure node-exporter.'
  ansible.builtin.import_tasks: 'configure-prometheus.yml'
