---
- name: 'Pre-setup: Create the prometheus group'
  ansible.builtin.group:
    name: "{{ services_prometheus_group }}"
    state: present
    system: true

- name: 'Pre-setup: Create the prometheus user'
  ansible.builtin.user:
    user: "{{ services_prometheus_user }}"
    groups:
      - "{{ services_prometheus_group }}"
    append: true
    shell: /usr/sbin/nologin
    system: true
    create_home: false
    home: "{{ services_prometheus_db_dir }}"

- name: 'Pre-setup: Prometheus data directory'
  ansible.builtin.file:
    path: "{{ services_prometheus_db_dir }}"
    state: directory
    owner: "{{ services_prometheus_user }}"
    group: "{{ services_prometheus_group }}"
    mode: '0755'

- name: 'Pre-setup: Prometheus configs'
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: "{{ services_prometheus_group }}"
    mode: '0770'
  with_items:
    - "{{ services_prometheus_config_dir }}"
    - "{{ services_prometheus_config_dir }}/rules"
    - "{{ services_prometheus_config_dir }}/file_sd"
